Find a strange inconsistency in the test results: tow different failures in non-randomized tests!
I first added more tests that passed immeadiately and therefore didn't reveal much, then tried reducing the currently failing test, and found that sometimes the two copies of the test even have different failures!

Specifically, running
```
cargo test --all --tests  -- tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_added_then_the_selection_is_changed
```
in the project root dietory repeatedly, sometimes shows each of the following results:
```
failures:

---- tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_added_t
hen_the_selection_is_changed stdout ----
[libs\editor\libs\text_buffer\./src\edit.rs:308] cur! { pos ! { l min_line, o 0 }, pos ! { l max_line, o 0 } } = cur!{l
 0 o 0 h l 1 o 0}
thread 'tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_adde
d_then_the_selection_is_changed' panicked at 'assertion failed: `(left != right)`
  left: `Some("")`,
 right: `Some("")`: (Index { generation: 1, index: 0 }, true)', libs\editor\./src\tests.rs:886:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_added_t
hen_the_selection_is_changed_reduction stdout ----
[libs\editor\libs\text_buffer\./src\edit.rs:308] cur! { pos ! { l min_line, o 0 }, pos ! { l max_line, o 0 } } = cur!{l
 0 o 0 h l 1 o 0}
thread 'tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_adde
d_then_the_selection_is_changed_reduction' panicked at 'assertion failed: `(left != right)`
  left: `Some("")`,
 right: `Some("")`: (Index { generation: 1, index: 0 }, true)', libs\editor\./src\tests.rs:886:13
```

```
failures:

---- tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_added_t
hen_the_selection_is_changed_reduction stdout ----
[libs\editor\libs\text_buffer\./src\edit.rs:308] cur! { pos ! { l min_line, o 0 }, pos ! { l max_line, o 0 } } = cur!{l
 0 o 0 h l 1 o 0}
thread 'tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_adde
d_then_the_selection_is_changed_reduction' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"¡"`: (Index { generation: 1, index: 1 }, false)', libs\editor\./src\tests.rs:894:13

---- tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_added_t
hen_the_selection_is_changed stdout ----
[libs\editor\libs\text_buffer\./src\edit.rs:308] cur! { pos ! { l min_line, o 0 }, pos ! { l max_line, o 0 } } = cur!{l
 0 o 0 h l 1 o 0}
thread 'tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_adde
d_then_the_selection_is_changed' panicked at 'assertion failed: `(left != right)`
  left: `Some("")`,
 right: `Some("")`: (Index { generation: 1, index: 0 }, true)', libs\editor\./src\tests.rs:886:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
failures:

---- tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_added_t
hen_the_selection_is_changed stdout ----
[libs\editor\libs\text_buffer\./src\edit.rs:308] cur! { pos ! { l min_line, o 0 }, pos ! { l max_line, o 0 } } = cur!{l
 0 o 0 h l 1 o 0}
thread 'tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_adde
d_then_the_selection_is_changed' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"¡"`: (Index { generation: 1, index: 1 }, false)', libs\editor\./src\tests.rs:894:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_added_t
hen_the_selection_is_changed_reduction stdout ----
[libs\editor\libs\text_buffer\./src\edit.rs:308] cur! { pos ! { l min_line, o 0 }, pos ! { l max_line, o 0 } } = cur!{l
 0 o 0 h l 1 o 0}
thread 'tests::tracking_what_the_view_says_gives_the_correct_idea_about_the_state_of_the_buffers_if_a_path_file_is_adde
d_then_the_selection_is_changed_reduction' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"¡"`: (Index { generation: 1, index: 1 }, false)', libs\editor\./src\tests.rs:894:13
```

The fourth possibilty these suggest does not seem to show up.